### PR TITLE
Add Node Modal

### PR DESCRIPTION
**Pull request by elraphty**
Created add node modal, and added animation to the sidebar

### CODE REVIEW

**Comment by kevkevinpal** [comment]
just a note when running `cargo run stack` it gave me a blank page and I was able to resolve it by going into `src/modes/stack/app/` and running `npm run build` not sure if this is something we want to run automatically

**Comment by Evanfeenstra** [comment]
@elraphty dont use the controls.ts file for the NewNode modal. That is for controls for individual nodes.

You dont need to use store for a simple variable in a component. Just use `let name = ''` in the component itself.

**Comment by Evanfeenstra** [comment]
Here are some hints:
```
import type {NodeType, Node} from './nodes'
  import {stack} from './store'

  let name = ''
  let type: NodeType = 'Btc'
  let links = []

  const availableConnections = {
    'Lnd':['Btc'],
    'Proxy':['Lnd'],
    'Relay':['Lnd', 'Proxy', 'Meme', 'Tribes']
  }

  $: connections = availableConnections[type]
  $: items = connections && connections.map(c=>({
    id: c,
    text: c
  }))

  function add() {
    const newNode: Node = {
      name, type, links, place: 'Internal'
    }
    stack.update(s=>({
      network: s.network,
      nodes: [...s.nodes, newNode]
    }))
  }
```

**Comment by Evanfeenstra** [comment]
@elraphty please see my last commit. Its like half as much code and a better UX

**Comment by elraphty** [comment]
> 

It's really nice using contains instead of ===, but do we have to use contains for the pubkey since no 2 pubkeys are the same.

**Pull request merged**
