### PR TITLE
Lndmanager

### PR DESCRIPTION
**Pull request by Evanfeenstra**
LND channel management

### CODE REVIEW

**Comment by Evanfeenstra** [comment]
@elraphty I merged master and made some changes

- can you build the Channel rows with mock data? I provided some as the `mockChannels` const in Lnd.svelte
- can you make it so when `Add Peer` or `Add Channel` is clicked, a UI form shows inside the sidebar (not a modal)
    - for `Add Peer` the fields are `pubkey` and `host`
    - for `Add Channel` the fields are `pubkey`, `amount`, and `sats per byte`

**Comment by elraphty** [comment]
> @elraphty I merged master and made some changes
> 
> * can you build the Channel rows with mock data? I provided some as the `mockChannels` const in Lnd.svelte
> * can you make it so when `Add Peer` or `Add Channel` is clicked, a UI form shows inside the sidebar (not a modal)
>   
>   * for `Add Peer` the fields are `pubkey` and `host`
>   * for `Add Channel` the fields are `pubkey`, `amount`, and `sats per byte`

Ok, @Evanfeenstra I'm working on it.

**Comment by Evanfeenstra** [comment]
@elraphty 

- the dot should be green if `active`, red if not
- the bars should represent the amount of liquidity on each side of the channel
    - example: "can receive" (remote balance) is 1000
    - "can send" (local balance) is 9000
    - the bar should be 10% on the left, and 90% on the right
- the bar should be red if the channel is "unbalanced". Meaning that there is <10% on either side of the channel. Orange if <20% on either side. Green if balanced
- you can put the pubkey into the "alias" section, use `text-overflow:ellipsis` to shorten it

I honestly think that <table> is not the way to go... things should line up with the line above, like in the mockup. Like all the bars should start at the same place.... If it were me, I would just use columns with set % widths

**Comment by elraphty** [comment]
> * text-overflow:ellipsis

**Comment by Evanfeenstra** [comment]
@elraphty 

- "can send" should be on the left, "can receive" on the right
- the bar should line up with the % of liquidity on that side of the channel
- start to build the "Add Peer" and "Add channel" hookups to the backend cmd.rs

**Comment by Evanfeenstra** [comment]
@elraphty maybe we need tabs in the LND interface for "general" and "channels".  other things LND should be able to do

- view all the fields from "GetInfo" call
- create address (so you can mine blocks to it)
- queryroutes (with address and amount, you can see if you have a route or not)

**Pull request merged**
