### PR TITLE
Tribes pagination and infinite scroll

### PR DESCRIPTION
**Pull request by elraphty**
This feature increases the user experience and load time on tribes by pagination the tribes data
@Evanfeenstra

### CODE REVIEW

**Comment by Evanfeenstra** [comment]
@elraphty in master branch i renamed the "modes" folder to "bin" (following Rust best practices). You can resolve these merge conflicts by just renaming your "modes" folder to "bin" also

**Comment by elraphty** [comment]
> @elraphty in master branch i renamed the "modes" folder to "bin" (following Rust best practices). You can resolve these merge conflicts by just renaming your "modes" folder to "bin" also

Ok, thanks @Evanfeenstra I will make the update now.

**Comment by Evanfeenstra** [comment]
@elraphty you committed a bunch of files generated by bitcoind (like `src/bin/demo/app/vol/bitcoind/regtest/.lock`)

Please remove all those files first using `git rm`. You should run the `--bin` from the top level of the repository, not from within a subdirectory

**Comment by elraphty** [comment]
> @elraphty you committed a bunch of files generated by bitcoind (like `src/bin/demo/app/vol/bitcoind/regtest/.lock`)
> 
> Please remove all those files first using `git rm`. You should run the `--bin` from the top level of the repository, not from within a subdirectory

Oh! ok, I will remove them now, I thought the .gitignore files already handled the volumes directory.

**Comment by elraphty** [comment]
> src/bin/demo/app/vol/bitcoind/

@Evanfeenstra I have removed the volume files, and also updated the .gitignore file to avoid future occurrences.

**Pull request merged**
