### PR TITLE
adding env vars to jarvis

### PR DESCRIPTION
**Pull request by kevkevinpal**

### CODE REVIEW

**Review by Evanfeenstra — COMMENTED** [review]
why two `RADAR_YOUTUBE_SCHEDULER_TIME_IN_SEC`? they are the same

**Comment by tomsmith8** [comment]
One of them should be twitter

**Comment by kevkevinpal** [comment]
oops I must have copied the same things twice, that's why we have reviews!

**Comment by kevkevinpal** [comment]
> why two `RADAR_YOUTUBE_SCHEDULER_TIME_IN_SEC`? they are the same
force pushed fix to [aab3cfb](https://github.com/stakwork/sphinx-swarm/pull/159/commits/aab3cfb39e4d6ba9688690029d6456be96ec58f3)

**Comment by tomsmith8** [comment]
What is the process for updating all swarms?

**Pull request merged**
